import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen max-w-4xl mx-auto bg-[#f7f9fc] flex flex-col">
        <header className="p-5 h-18">
          <nav>
            <Link
              href="/"
              className="mr-4 border-black border-2 p-2 rounded-md"
            >
              Home
            </Link>
            <Link
              href="/todos"
              className="border-black border-2 p-2 rounded-md"
            >
              Todos
            </Link>
          </nav>
        </header>
        <main className="p-5 grow">{children}</main>
        <footer className="text-center">Created by Kevin Tatooles</footer>
      </body>
    </html>
  );
}
