import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-full max-w-4xl mx-auto">
        <header className="p-5 h-18">
          <nav>
            <Link
              href="/"
              className="mr-4 border-black border-2 p-2 rounded-md"
            >
              Home
            </Link>
            <Link
              href="/todos"
              className="border-black border-2 p-2 rounded-md"
            >
              Todos
            </Link>
          </nav>
        </header>
        <main className="p-5 flex flex-col items-center">{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
